StartupEvents.registry("item", event => {
	//青铜锭相关物品
	event.create("gtlhardcore:bronze_billet_1")
		.displayName("§6青铜锭胚 §e(1/3)")
		.texture("gtlhardcore:item/bronze_billet")
		.tooltip("§7下一步: §c锻造锤敲击")
		.maxStackSize(64)
		.tag("gtlhardcore:billets")
	event.create("gtlhardcore:bronze_billet_2")
		.displayName("§6青铜锭胚 §e(2/3)")
		.texture("gtlhardcore:item/bronze_billet")
		.tooltip("§7下一步: §c高炉烧制")
		.maxStackSize(64)
		.tag("gtlhardcore:billets")
	//黏性树脂
	event.create("gtlhardcore:sticky_resin")
		.displayName("§6黏性树脂")
		.texture("gtceu:item/sticky_resin")
		.tooltip("§7此路不通,再次放入压缩机还原")
		.maxStackSize(64)
	//G钢锭相关物品
	event.create("gtlhardcore:hot_steel_billet_1")
		.displayName("§f热钢锭胚 §e(1/4)")
		.texture("gtlhardcore:item/hot_steel_billet")
		.tooltip("§7下一步: §c锻造锤敲击")
		.maxStackSize(64)
		.tag("gtlhardcore:billets")
	event.create("gtlhardcore:steel_billet_2")
		.displayName("§f钢锭胚 §e(2/4)")
		.texture("gtlhardcore:item/steel_billet")
		.tooltip("§7下一步: §c土高炉重新加热")
		.maxStackSize(64)
		.tag("gtlhardcore:billets")
	event.create("gtlhardcore:hot_steel_billet_3")
		.displayName("§f热钢锭胚 §e(3/4)")
		.texture("gtlhardcore:item/hot_steel_billet")
		.tooltip("§7下一步: §c锻造锤敲击")
		.maxStackSize(64)
		.tag("gtlhardcore:billets")
	//土高炉相关
	event.create("gtlhardcore:concrete_in_buckets")
		.displayName("§f桶装混凝土")
		.texture("gtlhardcore:item/concrete_in_buckets")
		.tooltip("§7来自梦想大师的恶意")
		.maxStackSize(1)
});